commerce/auctions/urls.py
from django.urls import path
from . import views

app_name = "auction"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("bids/<str:item_id>", views.bids, name="bids"),
    path("categories", views.categories, name="categories"),
    path("category/<str:category_id>", views.category, name="category"),
    path("comment/<str:item_id>", views.comment, name="comment"),
    path("listing/<str:item_id>", views.listing, name="listing"),
    path("view_watchlist", views.view_watchlist, name="view_watchlist"),
    path("watchlist/<str:item_id>", views.watchlist, name="watchlist"),
    path("new_listing", views.new_listing, name="new_listing")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime


class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=64)
    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    title = models.CharField(
        max_length=64,
        null=False
        )
    description = models.TextField(
        max_length=1024,
        null=False
        )
    starting_bid = models.DecimalField(
        max_digits=8,
        null=False,
        decimal_places=2
        )
    image_url = models.URLField(
        null=True
        )
    category = models.ForeignKey(
        Category, 
        on_delete=models.CASCADE,
        null=True,
        related_name="categories"
        )
    owner = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        null=False,
        related_name="owners"
        )
    winner = models.ForeignKey(
        User, 
        on_delete=models.DO_NOTHING,
        null=True,
        related_name="winner"
        )
    is_active = models.BooleanField(
        null=False,
        default = True
    )
    watchlist = models.ManyToManyField(User, blank=True, through='Watchlist', related_name="watchlist_items")
    bids = models.ManyToManyField(User, blank=True, through='Bid', related_name="bids_on_listing")
    comments = models.ManyToManyField(User, blank=True, through='Comment', related_name="comments_on_listing")
    def __str__(self):
        return f"{self.title}"

class Bid(models.Model):
    listing = models.ForeignKey(
        Listing, 
        default='0',
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        User, 
        default='0',
        on_delete=models.CASCADE
        )
    amount = models.DecimalField(
        max_digits=8,
        null=False,
        decimal_places=2,
        default='0'
        )
    bid_datetime = models.DateTimeField(
        auto_now_add=True
    )
    def __str__(self):
        return f"{self.user} bids {self.amount} for {self.listing}"

class Comment(models.Model):
    body = models.TextField(
        max_length=1024, 
        default=""
        )
    listing = models.ForeignKey(
        Listing, 
        default='0',
        on_delete=models.CASCADE,
        related_name="comment_listing"
        )
    user = models.ForeignKey(
        User, 
        default='0',
        on_delete=models.CASCADE
        )
    Comment_datetime = models.DateTimeField(
        auto_now_add=True
    )
    def __str__(self):
        return f"{self.user} on {self.listing}"

class Watchlist(models.Model):
    listing = models.ForeignKey(
        Listing, 
        default='0',
        on_delete=models.CASCADE,
        related_name="watchlist_listing"
        )
    user = models.ForeignKey(
        User, 
        default='0',
        on_delete=models.CASCADE,
        related_name="watchlist_user"
        )
    watchlist_datetime = models.DateTimeField(
        auto_now_add=True
    )
    def __str__(self):
        return f"Listing: {self.listing} | User: {self.user}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from .models import *
from decimal import Decimal
from django.db.models import Max

no_image_placeholder = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/480px-No_image_available.svg.png"

class NewListingForm(forms.Form):
    title = forms.CharField(
        label="", 
        widget=forms.TextInput(attrs={'placeholder':'Title'}),
        required=True
        )
    description = forms.CharField(
        label="", 
        widget=forms.Textarea(attrs={'placeholder':'Description'}),
        required=True
        )
    starting_bid = forms.DecimalField(
        label="",
        widget=forms.NumberInput(attrs={'placeholder': 'Starting bid'}),
        required=True
        )
    image_url = forms.URLField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'Image URL'}),
        required=False
        )
    category = forms.ModelChoiceField(
        label="", 
        empty_label='Select category',
        queryset=Category.objects.all(),
        required=False
        )
    # owner = forms.CharField(widget=forms.HiddenInput())


def index(request):
    all_listings = Listing.objects.all()
    return render(request, "auctions/index.html", {
        "listings": all_listings.filter(is_active=True)
    })

def new_listing(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)
        if form.is_valid():
            listing = Listing()
            listing.owner = request.user
            listing.title = form.cleaned_data["title"]
            listing.description = form.cleaned_data["description"]
            listing.starting_bid = form.cleaned_data["starting_bid"]
            listing.image_url = form.cleaned_data["image_url"]
            if listing.image_url == '':
                listing.image_url = no_image_placeholder
            listing.category = form.cleaned_data["category"]
            Listing.save(listing)
            all_listings = Listing.objects.all()
            return render(request, "auctions/index.html", {
                "new_listing_form": NewListingForm(),
                "listings": all_listings.filter(is_active=True),
                "message": "Succesfully created new listing."
    })
        else:
            return render(request, "auctions/new_listing.html", {
                "new_listing_form": NewListingForm(),
                "message": "Invalid input, please try again."
        })
    return render(request, "auctions/new_listing.html", {
        "new_listing_form": NewListingForm()
    })

def bids(request, item_id):
    if request.method == "POST":
        item = Listing.objects.get(pk=int(item_id))
        user = request.user
        if user.id is not None:
            on_watchlist = item.watchlist.filter(pk=int(user.id)).exists()
            amount = Decimal(request.POST["bid"].strip(' "'))
            if amount >= item.starting_bid:
                former_bids = Bid.objects.filter(listing=item_id)
                former_max_dict = former_bids.aggregate(Max('amount'))
                former_max_bid = former_max_dict.get("amount__max", 0.00)
                if former_max_bid is None or amount > former_max_bid:
                    bid = Bid()
                    bid.amount = amount
                    item.starting_bid = amount
                    item.winner = user
                    bid.listing = item
                    bid.user = user
                    bid.save()
                    item.save()
                    message = "Bid successfully placed."
                else:
                    message = "There is a higher bid already in the database."
            else:
                message = "Your bid must be higher than the current bid."
        else:
            message = "You must be logged in to place a bid."
            on_watchlist = False
    else:
        all_listings = Listing.objects.all()
        return render(request, "auctions/index.html", {
            "listings": all_listings.filter(is_active=True)
    })
    return render(request, "auctions/listing.html", {
        "listing": item,
        "on_watchlist": on_watchlist,
        "comments": Comment.objects.filter(listing=item),
        "message": message
        })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auction:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auction:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auction:index"))
    else:
        return render(request, "auctions/register.html")

def listing(request, item_id):
    item = Listing.objects.get(pk=int(item_id))
    comments = item.comments.all()
    user = request.user
    if request.method == "POST":
        item = Listing.objects.get(pk=int(item_id))
        user = request.user
        if user.id is not None and item.id is not None:
            item.is_active = False
            item.save()
            all_listings = Listing.objects.all()
            return render(request, "auctions/index.html", {
                "listings": all_listings.filter(is_active=True)
            })
    else:
        item = Listing.objects.get(pk=int(item_id))
        if user.id is not None:
            on_watchlist = item.watchlist.filter(pk=int(user.id)).exists()
            return render(request, "auctions/listing.html", {
                "listing": item,
                "comments": Comment.objects.filter(listing=item),
                "on_watchlist": on_watchlist
            })
    return render(request, "auctions/listing.html", {
        "listing": item,
        "comments": Comment.objects.filter(listing=item),
        "on_watchlist": False
    })

def watchlist(request, item_id):
        item = Listing.objects.get(pk=int(item_id))
        user = request.user
        if user.id is not None:
            on_watchlist = item.watchlist.filter(pk=int(user.id)).exists()
            if on_watchlist:
                item.watchlist.remove(user)
                on_watchlist = False
                return render(request, "auctions/listing.html", {
                    "listing": item,
                    "on_watchlist": on_watchlist,
                    "comments": Comment.objects.filter(listing=item),
                    "message": "Successfully removed from watchlist."
                })
            else:
                item.watchlist.add(user)
                on_watchlist = True
                return render(request, "auctions/listing.html", {
                    "listing": item,
                    "on_watchlist": on_watchlist,
                    "comments": Comment.objects.filter(listing=item),
                    "message": "Successfully added to watchlist."
                })
        return render(request, "auctions/listing.html", {
            "listing": item,
            "on_watchlist": False,
            "comments": Comment.objects.filter(listing=item),
            "message": "Successfully added to watchlist."
        })

def comment(request, item_id):
    if request.method == "POST":
        item = Listing.objects.get(pk=int(item_id))
        user = request.user
        if user.id is not None:
            on_watchlist = item.watchlist.filter(pk=int(user.id)).exists()
            cmt = request.POST["comment"]
            new_comment = Comment()
            new_comment.user = user
            new_comment.listing = item
            new_comment.body = cmt
            new_comment.save()
            message = "Comment successfully posted."
        else:
            message = "You must be logged in to post a comment."
            on_watchlist = False
    return render(request, "auctions/listing.html", {
        "listing": item,
        "comments": Comment.objects.filter(listing=item),
        "on_watchlist": on_watchlist,
        "message": message
        })

def view_watchlist(request):
    user_wl = Watchlist.objects.filter(user=request.user)
    user_wl_items = list()
    for entry in user_wl:
        user_wl_items.append(entry.listing)
    return render(request, "auctions/watchlist.html", {
        "user_watchlist": user_wl_items,
        })

def category(request, category_id):
    category_listings = Listing.objects.filter(category=category_id)
    category_listings = category_listings.filter(is_active=True)
    cat_name = Category.objects.get(id=category_id).name
    return render(request, "auctions/category.html", {

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Listings by categories</h2>
{% if message is not None %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
{% endif %}
    <div class="card-columns">
            {% for category in categories %}
                    <div class="card"">
                        {% comment %} <img class="card-img-top" src="{{ category.image_url }}" alt="Card image cap"> {% endcomment %}
                        <div class="card-body">
                            <h5 class="card-title">{{ category.name }}</h5>
                        </div> 
                        <div class="card-body">
                            <a href="{% url 'auction:category' category.id %}" class="btn btn-primary">See listings</a>
                        </div>
                    </div>
            {% endfor %}
    </div>
{% endblock %}

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings for category {{ category_name }}</h2>
{% if message is not None %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
{% endif %}
    <div class="card-columns">
        {% comment %} <div class="card-group" style="margin: 20px"> {% endcomment %}
            {% for listing in category_listings %}
                {% comment %} <div class="col-sm-4" style="margin: 20px"> {% endcomment %}
                    <div class="card"">
                     {% comment %} style="width: 18rem; {% endcomment %}
                        <img class="card-img-top" src="{{ listing.image_url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ listing.title }}</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ listing.description }}</li>
                            <li class="list-group-item">Current bid: ${{ listing.starting_bid }}</li>
                            <li class="list-group-item">Category: {{ listing.category }}</li>
                        </ul>
                        <div class="card-body">
                            <a href="{% url 'auction:listing' listing.id %}" class="btn btn-primary">See details</a>
                            {% comment %} <a href="{% url 'auction:watchlist' listing.id %}" class="btn btn-primary">Add to watchlist</a> {% endcomment %}
                        </div>
                    </div>
                {% comment %} </div> {% endcomment %}
            {% endfor %}
        {% comment %} </div> {% endcomment %}
    </div>
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
{% if message is not None %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
{% endif %}
    <div class="card-columns">
        {% comment %} <div class="card-group" style="margin: 20px"> {% endcomment %}
            {% for listing in listings %}
                {% comment %} <div class="col-sm-4" style="margin: 20px"> {% endcomment %}
                    <div class="card"">
                     {% comment %} style="width: 18rem; {% endcomment %}
                        <img class="card-img-top" src="{{ listing.image_url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ listing.title }}</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ listing.description }}</li>
                            <li class="list-group-item">Current bid: ${{ listing.starting_bid }}</li>
                            <li class="list-group-item">Category: {{ listing.category }}</li>
                        </ul>
                        <div class="card-body">
                            <a href="{% url 'auction:listing' listing.id %}" class="btn btn-primary">See details</a>
                            {% comment %} <a href="{% url 'auction:watchlist' listing.id %}" class="btn btn-primary">Add to watchlist</a> {% endcomment %}
                        </div>
                    </div>
                {% comment %} </div> {% endcomment %}
            {% endfor %}
        {% comment %} </div> {% endcomment %}
    </div>
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auction:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auction:view_watchlist' %}">View watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auction:categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auction:new_listing' %}">Create new listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auction:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auction:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auction:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if message is not None %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
{% endif %}
{% if not listing.is_active %}
    <div class="alert alert-danger" role="alert">
        Auction closed
    </div>
{% endif %}
{% if not listing.is_active and user.id is listing.winner_id%}
    <div class="alert alert-success" role="alert">
        Congratulations, you won the auction for this listing!
    </div>
{% endif %}

    <h2>{{ listing.title }} </h2>

    <div class="listing-img">
        <img class="card-img-top" src="{{ listing.image_url }}" alt="Card image cap">
        <li class="list-group-item">{{ listing.description }}</li>
        <li class="list-group-item">Current bid: ${{ listing.starting_bid }}</li>
        <li class="list-group-item">Category: {{ listing.category }}</li>
        <div class="card-body">
            {% if request.user.id is not None and listing.is_active %}
            <form action="{% url 'auction:bids' listing.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="mainContent">
                        <input class="form-control" type="number" min="1" step="any" name="bid" placeholder="Your bid in $">
                    </div>
                    <div class="sideContent">
                        <input class="btn btn-primary" type="submit" value="Confirm">
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </div>

<div class="listing-navbuttons">
    <a href="{% url 'auction:index' %}" class="btn btn-primary">Back to all listings</a>
    {% if request.user.id is not None and listing.is_active %}
        {% if on_watchlist %}
            <a href="{% url 'auction:watchlist' listing.id %}" class="btn btn-primary">Remove from watchlist</a>
        {% else %}
            <a href="{% url 'auction:watchlist' listing.id %}" class="btn btn-primary">Add to watchlist</a>
        {% endif %}
        {% if request.user.id is listing.owner.id %}
            <form action="{% url 'auction:listing' listing.id %}" method="post">
                <br></br>
                {% csrf_token %}
                <input class="btn btn-primary" type="submit" value="Close this auction">
            </form>
        {% endif %}
    {% endif %}
</div>
<br></br>
<br></br>

<h2>Comments</h2>

{% if listing.is_active and request.user.id is not None %}
    <form action="{% url 'auction:comment' listing.id %}" method="post">
        {% csrf_token %}
        <input class="form-control" type="text" name="comment" placeholder="Enter comment here">
        <input class="btn btn-primary" type="submit" value="Post comment">
    </form>
{% endif %}

{% for comment in comments %}
    <div class="card card-body bg-light">
      {{ comment.body|linebreaks }} - {{ comment.user }} ({{ comment.Comment_datetime }})
    </div>
{% endfor %}

{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

{% if message is not None %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
{% endif %}

    <form action="{% url 'auction:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auction:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/new_listing.html
{% extends "auctions/layout.html" %}
@login_required

{% block body %}
    <h2>New Listing</h2>
    {{ message }}
    <div class="form-group">
    <form action="{% url 'auction:new_listing' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
    {{ new_listing_form.as_p }}
    <input type="hidden" id="owner" name="owner" value="asdf">
    </div>
     <input class="btn btn-primary" type="submit" value="Submit">
    </form>
    </div>
{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auction:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auction:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

@login_required
{% block body %}
    <h2>My Watchlist</h2>
{% if message is not None %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
{% endif %}
    <div class="card-columns">
            {% for listing in user_watchlist %}
                    <div class="card"">
                        <img class="card-img-top" src="{{ listing.image_url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ listing.title }}</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ listing.description }}</li>
                            <li class="list-group-item">Current bid: ${{ listing.starting_bid }}</li>
                            <li class="list-group-item">Category: {{ listing.category }}</li>
                        </ul>
                        <div class="card-body">
                            <a href="{% url 'auction:listing' listing.id %}" class="btn btn-primary">See details</a>
                        </div>
                    </div>
            {% endfor %}
    </div>
{% endblock %}